### PR TITLE
Update site for kickoff

### PR DESCRIPTION
**Pull request by virtuald**
Will merge after kickoff.

### CODE REVIEW

**Comment by virtuald** [comment]
@PeterJohnson if you have anything to add to the release notice, feel free to add it/leave a comment here.

**Comment by PeterJohnson** [comment]
This is likely a separate bug, but the camera stuff depends on pynivision.  We'll need to update the installer to install it as well.

**Comment by PeterJohnson** [comment]
Another new thing that's available this year is numpy, but it'll take a paragraph to describe it and how to install it... worth including in the release notes for those who might be interested, though.

**Comment by virtuald** [comment]
Numpy et al might warrant a separate post?

**Comment by virtuald** [comment]
So, put a blurb in there to mention it now, and then write a bigger writeup and post it separately?

**Comment by PeterJohnson** [comment]
Seems reasonable.  Just a blurb now is fine; we can add details later.

**Pull request merged**
